server:
  port: 3000

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/uhsapp
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          auth0:
            domain: 'dev-qmx75p4q.us.auth0.com'
            client-id: 'sp9HNjFBFx3t1W726pTiVLMKq0ZHZP1T'
            client-secret: '******'
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            issuer-uri: https://dev-qmx75p4q.us.auth0.com/
  api-docs:
    enabled: true