server:
  port: 3000
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/humanitarius-db
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'https://dev-qmx75p4q.us.auth0.com/' # 'https://dev--ha3l5ql.us.auth0.com/'
      client:
        registration:
          auth0:
            domain: 'dev--ha3l5ql.us.auth0.com'
            client-id: 'HJGUEHnIb15zwigz4GeteOTAvb6OZuTn'
            client-secret: 'gmnFKp5cpKsDYTSEOrSe6_dkxy9dIdP5Kxm2cLY9Z86ZIpY-ZFMERJTtKHJMArY-'
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            issuer-uri: 'https://dev-qmx75p4q.us.auth0.com/'
#    oauth2:
#      client:
#        registration:
#          auth0:
#            domain: 'dev--ha3l5ql.us.auth0.com'
#            client-id: 'HJGUEHnIb15zwigz4GeteOTAvb6OZuTn'
#            client-secret: 'gmnFKp5cpKsDYTSEOrSe6_dkxy9dIdP5Kxm2cLY9Z86ZIpY-ZFMERJTtKHJMArY-'
#            scope:
#              - openid
#              - profile
#              - email
#        provider:
#          auth0:
#            issuer-uri: 'https://dev--ha3l5ql.us.auth0.com/'
  api-docs:
    enabled: true
auth0:
  audience: 'https://humanitarius/api'
